name: CI/CD Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout Code
        uses: actions/checkout@v2
      -name: Install Dependencies
        run: npm install
      -name: Run Tests
        run npm test
      -name: Build Docker Image
        run: docker build -t narshi/node-js-sample
      -name: Push Docker Image
        run: |
          docker login -u narshi --password-stdin
          docker push narshi/node-js-sample
